default: &default
  adapter: postgresql
  reconnect: true

development:
  <<: *default
  host: localhost
  database: graphql_dev
  username: siphon
  password: siphon
  sslmode: prefer

test:
  <<: *default
  database: graphql_test
  sslmode: prefer

production:
  <<: *default
  database: graphql
  sslmode: require
